language: scala

jdk:
  - openjdk8
  - openjdk11

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

script:
  - sbt headerCheck
  - sbt ^test

jobs:
  include:
    - stage: release
      jdk: openjdk8
      script: sbt ci-release

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier
