name: Release

on:
  push:
    branches: [master, main]
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK & sbt
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.8

    - name: Run tests
      run: |
        sbt headerCheck
        sbt ^test
        
    - name: Publish release
      run: sbt ci-release
      env:
        CI_RELEASE: '^publishSigned'
        CI_SNAPSHOT_RELEASE: '^publish'
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
